#ifndef __PROJET_ZZ1_CODE_ERREUR__
#define __PROJET_ZZ1_CODE_ERREUR__

#define CODE_ERR_GENERATION_DONJON 2
#define CODE_ERR_DIFFICULTE_INVALIDE 3
#define CODE_ERR_GENERATION_MONSTRE 4
#define CODE_ERR_GENERATION_PIECE 5
#define CODE_ERR_COMBAT_INATTENDU 6
#define CODE_ERR_CALC_POS_VOISIN 7
#define CODE_ERR_PIECE_INTROUV 8
#define CODE_ERR_POS_INTROUVABLE 9
#define CODE_ERR_GEN_TRAJ_ID_INV 10
#define CODE_ERR_GEN_TRAJ_M_MORT 11
#define CODE_ERR_EFFET_GEN 12
#define CODE_ERR_COLLISION_M_E 13

#endif
